[package]
name = "staking-miner"
version = "0.9.0"
authors = ["parity"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0" }
tokio = { version = "0.2", features = ["macros"] }
log = "0.4.11"
env_logger = "0.8.3"
structopt = "0.3.0"
jsonrpsee-ws-client = { version = "=0.2.0-alpha.6" }
jsonrpsee-types = { version = "=0.2.0-alpha.6" }
jsonrpsee = "=0.2.0-alpha.6"
serde_json = "1.0"
hex = "0.4.0"

remote-externalities = { git = "https://github.com/paritytech/substrate", branch = "kiz-staking-miner" }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "kiz-staking-miner" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "kiz-staking-miner" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "kiz-staking-miner" }
sp-npos-elections = { git = "https://github.com/paritytech/substrate", branch = "kiz-staking-miner" }

frame-election-provider-support = { git = "https://github.com/paritytech/substrate", branch = "kiz-staking-miner" }
pallet-election-provider-multi-phase = { git = "https://github.com/paritytech/substrate", branch = "kiz-staking-miner" }

core-primitives = { package = "polkadot-core-primitives", path = "../../core-primitives" }

polkadot-runtime = { path = "../../runtime/polkadot" }
kusama-runtime = { path = "../../runtime/kusama" }
westend-runtime = { path = "../../runtime/westend" }
